name: Auto deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to EC2
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ubuntu@ec2-3-38-113-63.ap-northeast-2.compute.amazonaws.com << 'EOF'
          cd ~/planner_server
          git stash save "Auto-stash before deployment"
          git pull

          pid=$(sudo lsof -t -i :1500)
          if [ -n "$pid" ]; then
            sudo kill -9 $pid
          fi
          screen -S server -X stuff "~/planner_server && python3 main.py\n"
          EOF